image: docker:24.0.7  # Use a specific Docker version instead of latest

services:
  - name: docker:24.0.7-dind  # Use a matching Docker-in-Docker version
    command: ["--tls=false"]  # Disable TLS to fix connection issues

variables:
  DOCKER_HOST: tcp://localhost:2375  # Connect to Docker-in-Docker
  DOCKER_TLS_CERTDIR: ""  # Ensure TLS is disabled
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase
  COMPOSE_HTTP_TIMEOUT: 300  # Avoid timeout issues

stages:
  - build
  - test

before_script:
  - apk add --no-cache docker-compose  # Install docker-compose
  - docker --version  # Check Docker installation
  - docker-compose --version  # Check docker-compose installation

build_job:
  stage: build
  script:
    - echo "Building the app..."
    - docker-compose build  # Build the Docker image
  tags:
    - docker

test_job:
  stage: test
  script:
    - echo "Starting services..."
    - docker-compose up -d
    - sleep 10  # Wait for PostgreSQL and Redis
    - curl -f http://localhost:8000/ || (echo "App failed to start" && exit 1)
  tags:
    - docker
  after_script:
    - docker-compose down  # Clean up after the test
