image: docker:24.0.7  # Use a Docker image

variables:
  DOCKER_HOST: unix:///var/run/docker.sock  # Use socket mounting
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to prevent authentication issues
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase
  COMPOSE_HTTP_TIMEOUT: 300  # Avoid timeout issues

stages:
  - build
  - test

before_script:
  - apk add --no-cache docker-compose  # Install docker-compose
  - docker --version  # Verify Docker installation
  - docker-compose --version  # Verify docker-compose installation
  - echo "Ensuring Docker is ready..."
  - sleep 5  # Give Docker time to initialize
  - docker info  # Debug Docker status

build_job:
  stage: build
  script:
    - echo "Building the app..."
    - docker-compose build  # Build the Docker image
  tags:
    - docker

test_job:
  stage: test
  script:
    - echo "Starting services..."
    - docker-compose up -d
    - sleep 10  # Wait for PostgreSQL and Redis
    - curl -f http://localhost:8000/ || (echo "App failed to start" && exit 1)
  tags:
    - docker
  after_script:
    - docker-compose down  # Clean up after the test
