image: docker:24.0.7  # Use a specific Docker image

variables:
  LOCAL_RUN: "false"  # Default (set to "true" locally)
  DOCKER_HOST: "tcp://docker:2375"  # Use TCP for Docker daemon
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - deploy

before_script:
  - if [[ "$LOCAL_RUN" == "true" ]]; then
      echo "Running locally - skipping Docker-in-Docker setup";
    else
      apk add --no-cache docker-compose curl;
      echo "Waiting for Docker to start...";
      sleep 20;
      docker info;
    fi

build_job:
  stage: build
  rules:
    - if: '$LOCAL_RUN == "false"'
  services:
    - name: docker:dind
      command: ["--tls=false"]
  script:
    - echo "Building Docker images..."
    - docker-compose build --no-cache  # Build images without cache

test:
  stage: test
  script:
    - echo "Starting services..."
    - docker-compose up -d
    - sleep 10
    - docker ps
    - docker-compose logs web

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying container..."
    - docker-compose up -d
    - docker ps
