image: docker:24.0.7  # Use a specific Docker image

variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"  # Use host Docker
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to prevent authentication issues
  POSTGRES_DB: mydatabase  # Database name for PostgreSQL
  POSTGRES_USER: user  # Username for PostgreSQL
  POSTGRES_PASSWORD: password  # Password for PostgreSQL
  REDIS_HOST: redis  # Redis hostname
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase  # Database connection URL
  COMPOSE_HTTP_TIMEOUT: 300  # Increase timeout for Docker Compose operations
  REGISTRY: https://registry.example.com/root/first_pipeline  # Docker registry URL
  IMAGE_NAME: first_pipeline  # Name of the Docker image to be built
  GITLAB_CI: "$CI_SERVER"  # Detect if running in GitLab CI/CD

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache docker-compose curl  # Install dependencies
  - docker --version  # Verify Docker installation
  - docker-compose --version  # Verify Docker Compose installation
  - echo "Ensuring Docker is ready..."
  - sleep 5  # Allow time for Docker to initialize
  - docker info  # Debugging: Display Docker system info

build_job:
  stage: build
  services:
    - name: docker:dind  # Enable Docker-in-Docker
      command: ["--tls=false"]  # Disable TLS
  script:
    - echo "Checking out the repository..."
    - ls -la  # Debugging: List files
    - |
      if test -f compose.yml; then
        echo "compose.yml exists!";
      else
        echo "ERROR: compose.yml is missing!";
        exit 1;
      fi
    - echo "Building the Docker images..."
    - docker-compose build --no-cache  # Build images without cache
  tags:
    - docker

test:
  stage: test
  services:
    - name: docker:dind
      command: ["--tls=false"]
  before_script:
    - apk add --no-cache docker-compose curl
  script:
    - echo "Starting Docker Compose services..."
    - docker-compose up -d
    - echo "Waiting for the web service to start..."
    - sleep 30  # Allow time for services to initialize
    - echo "Testing web service..."
    - docker-compose exec web curl -v http://0.0.0.0:5000 || (echo "Test failed!" && exit 1)
    - echo "Fetching web container logs..."
    - docker-compose logs web
  after_script:
    - echo "Stopping services..."
    - docker-compose down

deploy:
  stage: deploy
  only:
    - main
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo "Checking if image exists locally..."
    - docker images | grep $IMAGE_NAME || (echo "Image not found locally, exiting deployment" && exit 1)
    - echo "Stopping previous container..."
    - docker stop flask_app || true  # Stop running container if exists
    - docker rm flask_app || true  # Remove stopped container
    - echo "Deploying the container..."
    - docker-compose up -d
    - sleep 10  # Allow services to initialize
    - echo "Verifying running containers..."
    - docker ps
