image: docker:24.0.7  # Use a Docker image

variables:
  DOCKER_HOST: unix:///var/run/docker.sock  # Use socket mounting
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to prevent authentication issues
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase
  COMPOSE_HTTP_TIMEOUT: 300  # Avoid timeout issues
  REGISTRY: 192.168.1.4:5000/root/first_pipeline  # Update with your actual registry URL
  IMAGE_NAME: first_pipeline

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache docker-compose curl  # Install required tools
  - docker --version  # Verify Docker installation
  - docker-compose --version  # Verify docker-compose installation
  - echo "Ensuring Docker is ready..."
  - sleep 5  # Give Docker time to initialize
  - docker info  # Debug Docker status

build_job:
  stage: build
  services:
    - name: docker:dind  # ✅ Enable Docker-in-Docker
      command: ["--tls=false"]
  script:
    - echo "Checking out the repository..."
    - ls -la  # ✅ Debug: List all files
    - echo "Checking if compose.yml exists..."
    - test -f compose.yml && echo "compose.yml exists!" || (echo "ERROR:compose.yml is missing!" && exit 1)
    - echo "Pulling the latest image from the registry (if exists)..."
    - docker pull $REGISTRY:latest || echo "Image not found, building from scratch"
    - echo "Removing networks from compose.yml for build..."
    - sed '/networks:/,/my_network/d' compose.yml > compose.build.yml  # ✅ Remove networks from a copy
    - echo "Building the Docker images..."
    - docker-compose -f compose.build.yml build --no-cache
  tags:
    - docker

test:
  image: docker:24.0.7
  services:
    - docker:dind
  script:
    - echo "Starting Docker Compose services..."
    - docker-compose up -d
    - echo "Waiting for the web service to start..."
    - sleep 20  # Increased wait time
    - echo "Testing web service from inside the container..."
    - docker-compose exec web curl http://localhost:5000
    - echo "Fetching web container logs..."
    - docker logs first_pipeline-web-1
  after_script:
    - echo "Stopping services..."
    - docker-compose down

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Skipping registry authentication..."
    - echo "Checking if image exists locally..."
    - docker images | grep $IMAGE_NAME || (echo "Image not found locally, exiting deployment" && exit 1)
    - echo "Running the new container..."
    - docker stop flask_app || true
    - docker rm flask_app || true
    - docker run -d --name flask_app -p 5000:5000 $REGISTRY:latest
    - netstat -tulnp | grep 5000
