image: docker:24.0.7  # Use a Docker image

variables:
  DOCKER_HOST: unix:///var/run/docker.sock  # Use socket mounting
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to prevent authentication issues
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase
  COMPOSE_HTTP_TIMEOUT: 300  # Avoid timeout issues

stages:
  - build
  - test

before_script:
  - apk add --no-cache docker-compose  # Install docker-compose
  - docker --version  # Verify Docker installation
  - docker-compose --version  # Verify docker-compose installation
  - echo "Ensuring Docker is ready..."
  - sleep 5  # Give Docker time to initialize
  - docker info  # Debug Docker status

build_job:
  stage: build
  script:
    - docker network create my_network || true 
    - echo "Building the app..."
    - docker-compose build  # Build the Docker image
  tags:
    - docker
test_job:
  stage: test
  services:
    - name: docker:dind  # ✅ Enable Docker-in-Docker
      command: ["--tls=false"]
  script:
    - apk add --no-cache curl
    - echo "Building the Docker images..."
    - docker-compose build  # ✅ Build images without needing a network
    - echo "Creating Docker network..."
    - docker network create my_network || true  # ✅ Manually create the network
    - echo "Starting Docker Compose services..."
    - docker-compose up -d
    - echo "Checking Docker Networks..."
    - docker network ls  # ✅ Debug: Show available networks
    - echo "Checking Containers..."
    - docker ps  # ✅ Debug: List running containers
    - echo "Waiting for Flask app to be ready..."
    - timeout 60 sh -c 'until curl -sSf http://web:5000/; do sleep 5; done' || (echo "App failed to start" && exit 1)
    - echo "App is running!"
  tags:
    - docker
  after_script:
    - docker-compose down  # ✅ Stop containers after test



