image: docker:24.0.7

variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: first_pipeline
  CONTAINER_NAME: flask_app

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache docker-compose
  - docker --version
  - docker-compose --version

build_job:
  stage: build
  script:
    # Secure Docker Hub login with token
    - echo "$DOCKER_TOKEN" | docker login -u "ahmedheggy" --password-stdin
    
    # Build and push the image
    - docker build -t ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA
    
    # Also tag as 'latest' (optional)
    - docker tag ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA ahmedheggy/$IMAGE_NAME:latest
    - docker push ahmedheggy/$IMAGE_NAME:latest
  tags:
    - docker

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "$DOCKER_TOKEN" | docker login -u "ahmedheggy" --password-stdin
    - docker pull ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA
    
    # Stop and remove old container
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    
    # Create network if it doesn't exist
    - docker network create app_network || true
    
    # Run new container with correct database host
    - >
      docker run -d \
        --name $CONTAINER_NAME \
        --network app_network \
        -p 5000:5000 \
        -e POSTGRES_DB=$POSTGRES_DB \
        -e POSTGRES_USER=$POSTGRES_USER \
        -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
        -e REDIS_HOST=first-pipeline-redis-1 \
        -e DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@first-pipeline-db-1:5432/$POSTGRES_DB \
        ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA
    
    # Connect existing services to the network
    - docker network connect app_network first-pipeline-db-1
    - docker network connect app_network first-pipeline-redis-1
    
    # Verify
    - sleep 10
    - docker ps
    - docker logs $CONTAINER_NAME --tail 50