image: python:3.11  # Use an official Python image

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Building the app..."
    - python --version
  tags:
    - docker

test_job:
  stage: test
  script:
    - echo "Testing the app..."
    - python app.py  # Run your application
  tags:
    - docker
