image: docker:24.0.7

variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_TLS_CERTDIR: ""
  REGISTRY: docker.io
  IMAGE_NAME: first_pipeline

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache docker-compose openssh-client
  - docker --version
  - docker-compose --version

build_job:
  stage: build
  services:
    - name: docker:dind
      command: ["--tls=false"]
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $DOCKER_USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA
  tags:
    - docker

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Logging in to Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Pulling the image from Docker Hub..."
    - docker pull $DOCKER_USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA
    - echo "Stopping previous container..."
    - docker stop flask_app || true
    - docker rm flask_app || true
    - echo "Running the new container..."
    - docker run -d --name flask_app -p 5000:5000 $DOCKER_USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA
    - echo "Verifying running containers..."
    - docker ps
  tags:
    - docker