image: docker:24.0.7  # Use Docker image

variables:
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to prevent authentication issues
  COMPOSE_HTTP_TIMEOUT: 300  # Increase timeout for Docker Compose operations
  LOCAL_DOCKER: "unix:///var/run/docker.sock"  # Default Docker socket for local runs
  CI_DOCKER: "tcp://docker:2375"  # Docker socket for GitLab CI

stages:
  - build
  - test
  - deploy

before_script:
  - |
    if [[ "$LOCAL_RUN" == "true" ]]; then 
      echo "Running locally - using system Docker";
      export DOCKER_HOST="$LOCAL_DOCKER"
    else
      echo "Running in GitLab CI - enabling Docker-in-Docker";
      export DOCKER_HOST="$CI_DOCKER"
      apk add --no-cache docker-compose curl  # Install dependencies
      echo "Waiting for Docker to start...";
      sleep 10;
      docker info || (echo "Docker is not running!" && exit 1)
    fi

build_job:
  stage: build
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
  variables:
    DOCKER_HOST: "$CI_DOCKER"
  script:
    - echo "Checking if Docker is running..."
    - docker info || (echo "Docker is NOT running!" && exit 1)
    - echo "Building the Docker images..."