image: docker:24.0.7  # Use a Docker image

variables:
  DOCKER_HOST: unix:///var/run/docker.sock  # Use socket mounting
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to prevent authentication issues
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase
  COMPOSE_HTTP_TIMEOUT: 300  # Avoid timeout issues

stages:
  - build
  - test

before_script:
  - apk add --no-cache docker-compose  # Install docker-compose
  - docker --version  # Verify Docker installation
  - docker-compose --version  # Verify docker-compose installation
  - echo "Ensuring Docker is ready..."
  - sleep 5  # Give Docker time to initialize
  - docker info  # Debug Docker status

build_job:
  stage: build
  services:
    - name: docker:dind  # ✅ Enable Docker-in-Docker
      command: ["--tls=false"]
  script:
    - apk add --no-cache curl
    - echo "Checking out the repository..."
    - ls -la  # ✅ Debug: List all files to verify `compose.yml` is present
    - |
      if test -f compose.yml; then
        echo "compose.yml exists!";
      else
        echo "ERROR: compose.yml is missing!";
        exit 1;
      fi
    - echo "Removing networks from compose.yml for build..."
    - sed '/networks:/,/my_network/d' compose.yml > compose.build.yml  # ✅ Remove networks from a copy
    - echo "Building the Docker images..."
    - docker-compose -f compose.build.yml build --no-cache
  tags:
    - docker

test_job:
  stage: test
  services:
    - name: docker:dind
      command: ["--tls=false"]
  script:
    - apk add --no-cache curl
    - echo "Creating Docker network..."
    - docker network create my_network || true  # ✅ Create the network manually if it doesn't exist
    - echo "Starting Docker Compose services..."
    - docker-compose up -d
    - echo "Checking Docker Networks..."
    - docker network ls  # ✅ Debugging: Show available networks
    - echo "Checking Containers..."
    - docker ps  # ✅ Debugging: List running containers
    - echo "Waiting for Flask app to be ready..."
    - timeout 60 sh -c 'until curl -sSf http://web:5000/; do sleep 5; done' || (echo "App failed to start" && exit 1)
    - echo "App is running!"
  tags:
    - docker
  after_script:
    - docker-compose down  # ✅ Stop containers after test

