image: docker:24.0.7  # Use a Docker image

variables:
  DOCKER_HOST: unix:///var/run/docker.sock  # Use socket mounting
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to prevent authentication issues
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase
  COMPOSE_HTTP_TIMEOUT: 300  # Avoid timeout issues

stages:
  - build
  - test

before_script:
  - apk add --no-cache docker-compose  # Install docker-compose
  - docker --version  # Verify Docker installation
  - docker-compose --version  # Verify docker-compose installation
  - echo "Ensuring Docker is ready..."
  - sleep 5  # Give Docker time to initialize
  - docker info  # Debug Docker status

build_job:
  stage: build
  services:
    - name: docker:dind  # ✅ Enable Docker-in-Docker
      command: ["--tls=false"]
  script:
    - apk add --no-cache curl
    - echo "Checking out the repository..."
    - ls -la  # ✅ Debug: List all files to verify `compose.yml` is present
    - |
      if test -f compose.yml; then
        echo "compose.yml exists!";
      else
        echo "ERROR: compose.yml is missing!";
        exit 1;
      fi
    - echo "Removing networks from compose.yml for build..."
    - sed '/networks:/,/my_network/d' compose.yml > compose.build.yml  # ✅ Remove networks from a copy
    - echo "Building the Docker images..."
    - docker-compose -f compose.build.yml build --no-cache
  tags:
    - docker

test_job:
  stage: test
  image: docker:24.0.7  # ✅ Use the latest stable Docker image
  variables:
    DOCKER_HOST: "tcp://host.docker.internal:2375"  # ✅ Use host's Docker daemon
    DOCKER_DRIVER: "overlay2"
    COMPOSE_PROJECT_NAME: "my_app_test"  # ✅ Unique project name to avoid conflicts
  before_script:
    - apk add --no-cache curl jq docker-cli-compose  # ✅ Ensure dependencies
    - echo "Ensuring Docker is ready..."
    - sleep 10
    - docker info || (echo "Docker failed to connect"; exit 1)
  script:
    - echo "Checking Docker Networks..."
    - docker network ls
    - echo "Ensuring my_network exists..."
    - docker network create my_network || echo "Network already exists"
    - echo "Starting Docker Compose services..."
    - docker-compose up -d --remove-orphans
    - echo "Checking Running Containers..."
    - docker ps -a
    - echo "Waiting for services to be healthy..."
    - timeout 60 sh -c 'until docker-compose ps | grep "healthy"; do sleep 5; done' || (echo "Services failed to start"; docker-compose logs; exit 1)
    - echo "Running tests..."
    - docker-compose exec -T <service_name> <test_command>  # ✅ Replace with your test command
  after_script:
    - echo "Tearing down Docker Compose services..."
    - docker-compose down --remove-orphans || true

debug_networks:
  stage: test
  services:
    - name: docker:dind  # ✅ Enable Docker-in-Docker
      command: ["--tls=false"]
  script:
    - echo "Checking Docker Networks..."
    - docker network ls  # ✅ List available networks
    - echo "Inspecting my_network..."
    - docker network inspect my_network || echo "Network does not exist"
  tags:
    - docker
  when: manual  # ✅ Allows you to manually trigger the job in GitLab UI
  allow_failure: true  # ✅ Prevents pipeline from failing while debugging

