image: docker:24.0.7

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: first_pipeline

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache docker-compose
  - docker --version

build_job:
  stage: build
  script:
    # Secure login using access token
    - echo "$DOCKER_TOKEN" | docker login -u "ahmedheggy" --password-stdin
    - docker build -t ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA
  tags:
    - docker

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "$DOCKER_TOKEN" | docker login -u "ahmedheggy" --password-stdin
    - docker pull ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA
    - docker stop flask_app || true
    - docker rm flask_app || true
    - docker run -d --name flask_app -p 5000:5000 ahmedheggy/$IMAGE_NAME:$CI_COMMIT_SHA
    - docker ps
  tags:
    - docker