image: docker:latest  # Use a Docker image that supports Docker-in-Docker

services:
  - docker:dind  # Enable Docker-in-Docker (DinD)

variables:
  DOCKER_HOST: tcp://docker:2375  # Ensure the runner communicates with Docker-in-Docker
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to avoid permission issues
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase
  COMPOSE_HTTP_TIMEOUT: 300  # Prevent timeout issues

stages:
  - build
  - test

before_script:
  - apk add --no-cache docker-compose  # Ensure docker-compose is installed
  - docker-compose --version  # Check if docker-compose is working
  - docker info  # Debug Docker status

build_job:
  stage: build
  script:
    - echo "Building the app..."
    - docker-compose build  # Build the Docker image
  tags:
    - docker

test_job:
  stage: test
  script:
    - echo "Starting services..."
    - docker-compose up -d  # Start services in detached mode
    - sleep 10  # Wait for services to be ready
    - echo "Running tests..."
    - curl -f http://localhost:8000/ || (echo "App failed to start" && exit 1)
  tags:
    - docker
  after_script:
    - docker-compose down  # Stop services after the test
