image: docker:24.0.7  # Use a Docker image

variables:
  DOCKER_HOST: unix:///var/run/docker.sock  # Use socket mounting
  DOCKER_TLS_CERTDIR: ""  # Disable TLS to prevent authentication issues
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  REDIS_HOST: redis
  DATABASE_URL: postgresql://user:password@db:5432/mydatabase
  COMPOSE_HTTP_TIMEOUT: 300  # Avoid timeout issues

stages:
  - build
  - test

before_script:
  - apk add --no-cache docker-compose  # Install docker-compose
  - docker --version  # Verify Docker installation
  - docker-compose --version  # Verify docker-compose installation
  - echo "Ensuring Docker is ready..."
  - sleep 5  # Give Docker time to initialize
  - docker info  # Debug Docker status

build_job:
  stage: build
  script:
    - echo "Building the app..."
    - docker-compose build  # Build the Docker image
  tags:
    - docker

test_job:
  stage: test
  script:
    - apk add --no-cache curl
    - echo "Starting Docker Compose services..."
    - docker-compose up -d
    - echo "Waiting for Flask app to be ready..."
    - docker ps -a  #  Check docker containers 
    - echo "Checking Flask container logs..."
    - timeout 30 sh -c 'until curl -sSf http://host.docker.internal:8000/; do sleep 5; done' || (echo "App failed to start" && exit 1)
    - echo "App is running!"
  tags:
    - docker
  after_script:
    - docker-compose down
