image: docker:24.0.7

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  REGISTRY: docker.io
  IMAGE_NAME: first_pipeline

stages:
  - build
  - deploy

services:
  - name: docker:dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]

before_script:
  - apk add --no-cache docker-compose openssh-client
  - docker --version
  - docker-compose --version

build_job:
  stage: build
  script:
    - echo "Logging in to Docker Hub..."
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $DOCKER_USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA
  tags:
    - docker

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Logging in to Docker Hub..."
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - echo "Pulling the image..."
    - docker pull $DOCKER_USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA
    - echo "Stopping previous container..."
    - docker stop flask_app || true
    - docker rm flask_app || true
    - echo "Running new container..."
    - docker run -d --name flask_app -p 5000:5000 $DOCKER_USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA
    - echo "Verifying containers..."
    - docker ps
  tags:
    - docker