version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "sleep 10 && python app.py"  # Wait for DB & Redis before starting

  db:
    image: postgres:15  # Use a stable version
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine  # Use a smaller, optimized Redis image
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
