version: '3.8'

services:
  web:
    image: ahmedheggy/first_pipeline:${TAG:-latest}  # Uses the image from Docker Hub
    ports:
      - "8000:5000"
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env  # Ensure .env is available on the deployment server

  db:
    image: postgres:latest
    restart: always
    networks:
      - my_network
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    restart: always
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:

networks:
  my_network:
    driver: bridge